
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    servicename: {{ .Values.service.name }}
